const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('passsa', {
  register: (email, password) => ipcRenderer.invoke('auth:register', { email, password }),
  login: (email, password) => ipcRenderer.invoke('auth:login', { email, password }),
  googleLogin: () => ipcRenderer.invoke('auth:google-start'),
  googleComplete: (challengeId, password) => ipcRenderer.invoke('auth:google-complete', { challengeId, password }),
  session: () => ipcRenderer.invoke('auth:session'),
  logout: () => ipcRenderer.invoke('auth:logout'),
  lock: () => ipcRenderer.invoke('auth:lock'),
  onLocked: (callback) => ipcRenderer.on('session:locked', (_event, reason) => callback(reason)),
  syncNow: () => ipcRenderer.invoke('sync:now'),
  disconnectGoogle: () => ipcRenderer.invoke('sync:disconnect'),
  listItems: () => ipcRenderer.invoke('vault:list'),
  getItem: (id) => ipcRenderer.invoke('vault:get', id),
  addItem: (item) => ipcRenderer.invoke('vault:add', item),
  updateItem: (item) => ipcRenderer.invoke('vault:update', item),
  toggleFavorite: (id) => ipcRenderer.invoke('vault:favorite', id),
  deleteItem: (id) => ipcRenderer.invoke('vault:delete', id),
  restoreItem: (id) => ipcRenderer.invoke('vault:restore', id),
  purgeItem: (id) => ipcRenderer.invoke('vault:purge', id),
  bulkUpdate: (ids, changes) => ipcRenderer.invoke('vault:bulk-update', ids, changes),
  bulkDelete: (ids) => ipcRenderer.invoke('vault:bulk-delete', ids),
  bulkRestore: (ids) => ipcRenderer.invoke('vault:bulk-restore', ids),
  bulkPurge: (ids) => ipcRenderer.invoke('vault:bulk-purge', ids),
  copyEntrySecret: (id, field) => ipcRenderer.invoke('vault:copy-entry', id, field),
  listCategories: () => ipcRenderer.invoke('category:list'),
  listCategoryIcons: () => ipcRenderer.invoke('category:icons'),
  createCategory: (category) => ipcRenderer.invoke('category:create', category),
  updateCategory: (category) => ipcRenderer.invoke('category:update', category),
  deleteCategory: (id) => ipcRenderer.invoke('category:delete', id),
  copySecret: (value) => ipcRenderer.invoke('vault:copy', value),
});
