const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('passsa', {
  register: (username, password) => ipcRenderer.invoke('auth:register', { username, password }),
  login: (username, password) => ipcRenderer.invoke('auth:login', { username, password }),
  devBypassStatus: () => ipcRenderer.invoke('auth:dev-bypass-status'),
  devBypassLogin: () => ipcRenderer.invoke('auth:dev-bypass-login'),
  googleLogin: () => ipcRenderer.invoke('auth:google-start'),
  googleComplete: (challengeId, password, localIdentifier) => ipcRenderer.invoke('auth:google-complete', { challengeId, password, localIdentifier }),
  copyTwoFactorSetupKey: (challengeId) => ipcRenderer.invoke('auth:2fa-copy-setup-key', { challengeId }),
  twoFactorComplete: (challengeId, code, recovery = false, setupSecret = '') => ipcRenderer.invoke('auth:2fa-complete', { challengeId, code, recovery, setupSecret }),
  twoFactorStatus: () => ipcRenderer.invoke('auth:2fa-status'),
  twoFactorSetupStart: () => ipcRenderer.invoke('auth:2fa-setup-start'),
  twoFactorDisable: (password, code) => ipcRenderer.invoke('auth:2fa-disable', { password, code }),
  directLoginStatus: () => ipcRenderer.invoke('auth:direct-login-status'),
  directLoginEnable: (password) => ipcRenderer.invoke('auth:direct-login-enable', { password }),
  directLoginDisable: () => ipcRenderer.invoke('auth:direct-login-disable'),
  directLoginUnlock: () => ipcRenderer.invoke('auth:direct-login-unlock'),
  session: () => ipcRenderer.invoke('auth:session'),
  logout: () => ipcRenderer.invoke('auth:logout'),
  lock: () => ipcRenderer.invoke('auth:lock'),
  helloStatus: (username) => ipcRenderer.invoke('auth:hello-status', { username }),
  helloEnable: (currentPassword) => ipcRenderer.invoke('auth:hello-enable', { currentPassword }),
  helloDisable: () => ipcRenderer.invoke('auth:hello-disable'),
  helloUnlock: (username) => ipcRenderer.invoke('auth:hello-unlock', { username }),
  setWindowMode: (mode) => ipcRenderer.invoke('window:set-mode', mode),
  minimizeWindow: () => ipcRenderer.invoke('window:minimize'),
  toggleMaximizeWindow: () => ipcRenderer.invoke('window:toggle-maximize'),
  closeWindow: () => ipcRenderer.invoke('window:close'),
  setTheme: (theme, palette) => ipcRenderer.invoke('window:set-theme', { theme, palette }),
  getAppSettings: () => ipcRenderer.invoke('settings:get-app'),
  setAppSettings: (input) => ipcRenderer.invoke('settings:set-app', input),
  changePassword: (input) => ipcRenderer.invoke('auth:change-password', input),
  exportVault: (input) => ipcRenderer.invoke('vault:export', input),
  importVault: (input) => ipcRenderer.invoke('vault:import', input),
  onLocked: (callback) => ipcRenderer.on('session:locked', (_event, reason) => callback(reason)),
  onQuickAccessOpen: (callback) => ipcRenderer.on('quick-access:open-item', (_event, id) => callback(id)),
  syncNow: () => ipcRenderer.invoke('sync:now'),
  syncInfo: () => ipcRenderer.invoke('sync:info'),
  disconnectGoogle: () => ipcRenderer.invoke('sync:disconnect'),
  s3SyncInfo: () => ipcRenderer.invoke('s3:info'),
  connectS3: (input) => ipcRenderer.invoke('s3:connect', input),
  s3SyncNow: (password = '') => ipcRenderer.invoke('s3:sync-now', { password }),
  disconnectS3: () => ipcRenderer.invoke('s3:disconnect'),
  listItems: () => ipcRenderer.invoke('vault:list'),
  getItem: (id) => ipcRenderer.invoke('vault:get', id),
  listTotpCodes: (ids) => ipcRenderer.invoke('vault:totp-codes', ids),
  addItem: (item) => ipcRenderer.invoke('vault:add', item),
  updateItem: (item) => ipcRenderer.invoke('vault:update', item),
  toggleFavorite: (id) => ipcRenderer.invoke('vault:favorite', id),
  deleteItem: (id) => ipcRenderer.invoke('vault:delete', id),
  restoreItem: (id) => ipcRenderer.invoke('vault:restore', id),
  purgeItem: (id) => ipcRenderer.invoke('vault:purge', id),
  bulkUpdate: (ids, changes) => ipcRenderer.invoke('vault:bulk-update', ids, changes),
  bulkDelete: (ids) => ipcRenderer.invoke('vault:bulk-delete', ids),
  bulkRestore: (ids) => ipcRenderer.invoke('vault:bulk-restore', ids),
  bulkPurge: (ids) => ipcRenderer.invoke('vault:bulk-purge', ids),
  copyEntrySecret: (id, field) => ipcRenderer.invoke('vault:copy-entry', id, field),
  copyTotpCode: (id) => ipcRenderer.invoke('vault:copy-totp', id),
  listCategories: () => ipcRenderer.invoke('category:list'),
  listCategoryIcons: () => ipcRenderer.invoke('category:icons'),
  createCategory: (category) => ipcRenderer.invoke('category:create', category),
  updateCategory: (category) => ipcRenderer.invoke('category:update', category),
  deleteCategory: (id) => ipcRenderer.invoke('category:delete', id),
  copySecret: (value) => ipcRenderer.invoke('vault:copy', value),
});
